name: Auto Process DNS

on:
  workflow_dispatch: # Cho phép bấm chạy thủ công
  schedule:
    - cron: '0 */6 * * *' # Chạy mỗi 6 tiếng

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cài đặt Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện requests
        run: pip install requests

      - name: Chạy script xử lý
        run: python z_code_process_dns.py

      - name: Lưu file vào Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add dns_VN.txt
          
          # Kiểm tra nếu có thay đổi thì mới commit
          if git diff --staged --quiet; then
            echo "Không có IP mới nào được tìm thấy."
          else
            # Tránh xung đột bằng cách pull trước khi push
            git pull origin main --rebase
            git commit -m "Cập nhật danh sách IP: $(date +'%d-%m-%Y %H:%M')"
            git push origin main
          fi
