name: Auto Process DNS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cài đặt Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện
        run: pip install requests

      - name: Chạy script xử lý
        run: python z_code_process_dns.py

      - name: Lưu file vào Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Thêm file vào vùng chờ
          git add dns_VN.txt

          # Kiểm tra xem thực sự có thay đổi nội dung không
          if git diff --staged --quiet; then
            echo "Không có thay đổi nào để cập nhật."
          else
            git commit -m "Cập nhật list DNS: $(date +'%d-%m-%Y %H:%M')"
            
            # Kéo dữ liệu mới nhất về trước để tránh xung đột
            git pull origin main --rebase
            
            # Đẩy lên nhánh main một cách tường minh
            git push origin HEAD:main
          fi
